### ISSUE TITLE
ERROR [homebridge-cbus] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

### ISSUE THREAD

**Issue by tbgk** [anthonywebb/homebridge-cbus#147]
Error stopping Homebridge working..

[homebridge-cbus] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

**Comment by DarylMc** [comment]
Are you using CGate 3.2?
If so you will need to change some text in CGate config
https://github.com/anthonywebb/homebridge-cbus/issues/140#issuecomment-1878031175

**Comment by tbgk** [comment]
Thanks Daryl, I am using Cgate ver 2.11.4 and it show Clipsal in the config file?
Any other ideas?

**Comment by DarylMc** [comment]
You can see in that issue I was getting a similar message when Homebridge wasn't getting the expected reply from CGate.
Maybe have a look at the CGate logs.
If you are using a raspberry pi there is a script here which should make the whole setup easy.

https://github.com/greiginsydney/Homebridge-cbus-installer/blob/master/SETUP.md

**Comment by tbgk** [comment]
I have reinstalled using above script from greiginsydney, still no luck, the error log is as follows:

[31/07/2024, 15:29:08] [Homebridge UI] Homebridge restart request received
[31/07/2024, 15:29:08] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[31/07/2024, 15:29:08] [Homebridge UI] Sending SIGTERM to Homebridge
[31/07/2024, 15:29:08] Got SIGTERM, shutting down Homebridge...
[31/07/2024, 15:29:09] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/var/lib/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/var/lib/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/var/lib/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/var/lib/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[31/07/2024, 15:29:13] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[31/07/2024, 15:29:18] [HB Supervisor] Restarting Homebridge...
[31/07/2024, 15:29:18] [HB Supervisor] Starting Homebridge with extra flags: -P /var/lib/homebridge/node_modules -D --strict-plugin-resolution
[31/07/2024, 15:29:19] [HB Supervisor] Started Homebridge v1.8.3 with PID: 20776
[31/07/2024, 15:29:20] Loaded config.json with 0 accessories and 2 platforms.
[31/07/2024, 15:29:20] Loaded 0 cached accessories from cachedAccessories.
[31/07/2024, 15:29:20] ---
[31/07/2024, 15:29:20] Loaded plugin: homebridge-cbus@1.1.0
[31/07/2024, 15:29:20] Registering platform 'homebridge-cbus.CBus'
[31/07/2024, 15:29:20] ---
[31/07/2024, 15:29:20] Loaded plugin: homebridge-daikin-local-platform@1.1.0
[31/07/2024, 15:29:20] Registering platform 'homebridge-daikin-local-platform.Daikin Local Platform'
[31/07/2024, 15:29:20] ---
[31/07/2024, 15:29:20] Loaded plugin: homebridge-lgwebos-tv@1.5.1
[31/07/2024, 15:29:20] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[31/07/2024, 15:29:20] ---
[31/07/2024, 15:29:20] Loading 2 platforms...
[31/07/2024, 15:29:20] [CBus] Initializing homebridge-cbus.CBus platform...
2024-07-31T05:29:20.645Z cbus:client Opening connection to C-Gate…
2024-07-31T05:29:20.655Z cbus:client C-Gate connection open.
[31/07/2024, 15:29:40] [homebridge-cbus] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.

Any help appreciated.
Thanks

**Comment by DarylMc** [comment]
Did you see Greig's script will create and populate the config.json file?
I see you have some other plugins so I'm not sure how that would work if you already had them setup.
Perhaps just start again with a fresh sd card and skip the other plugins.
If that's the problem then we can try figure a way around that.

**Comment by DarylMc** [comment]
Which raspberry pi and which CBus interface are you using?
