### ISSUE TITLE
TypeError terminates homebridge-cbus on start up

### ISSUE THREAD

**Issue by MattSwinn** [anthonywebb/homebridge-cbus#31]
Hi

I'm new to homebridge, homebridge-cbus and CGate.

When I go to start homebridge, I get an error but I don't understand what it means or how to fix it.

The output is as follows.
```
Matthews-iMac:/ Matt$ homebridge
[3/11/2017, 9:22:20 PM] Loaded plugin: homebridge-cbus
[3/11/2017, 9:22:20 PM] Registering platform 'homebridge-cbus.CBus'
[3/11/2017, 9:22:20 PM] ---
[3/11/2017, 9:22:20 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/11/2017, 9:22:20 PM] ---
[3/11/2017, 9:22:20 PM] Loading 1 platforms...
[3/11/2017, 9:22:20 PM] [CBus] Initializing homebridge-cbus.CBus platform...
cbus:client Opening connection to C-Gate… +0ms
[3/11/2017, 9:22:20 PM] Loading 0 accessories...
cbus:client C-Gate connection open. +4ms
cbus:client Connected to C-Gate server v2.10.6 (build 3145), syntax v1.0 +2ms
cbus:client Configuring C-Gate session… +0ms
cbus:client C-Gate session estabished and configured at 20023:127.0.0.1 +1ms
cbuslatform Loading the accessories list… +0ms
/usr/local/lib/node_modules/homebridge-cbus/index.js:186
for (let config of this.config.accessories) {
^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at CBusPlatform._createAccessories (/usr/local/lib/node_modules/homebridge-cbus/index.js:186:30)
at CBusPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/index.js:166:28)
at Carrier.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:195:6)
at emitOne (events.js:96:13)
at Carrier.emit (events.js:188:7)
at /usr/local/lib/node_modules/homebridge-cbus/node_modules/carrier/lib/carrier.js:24:12
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
Matthews-iMac:/ Matt$
```
My config.json is as follows:

```
{
"bridge": {
"name": "My house",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"description": "HomeKit API config file.",


"platforms": [
{
"platform": "homebridge-cbus.CBus",
"name": "CBus",
"client_ip_address": "127.0.0.1",
"client_controlport": 20023,
"client_cbusname": "SWINN",
"client_network": 254,
"client_application": 56,
"client_debug": true,

"accesories": [
{ "type": "light", "network": "254", "application": "56", "id": 53, "name": "Study" }
]

}
],
"accessories": [ ]
}
```
Finally, for completeness, here is a snippet from the CGate logs that appears to show a successful request from homebridge-cbus to CGate and provision of accessories data by CGate to homebridge-cbus.

```
20170312-214659 803 cmd5 - Host:/127.0.0.1 opened command interface from port: 49962
20170312-214659 899 sys Debug: New Command Context: cc013 = AccessContext Session /127.0.0.1#6
20170312-214659 766 cmd5 - Response: 201 Service ready: Clipsal C-Gate Version: v2.10.6 (build 3145) #cmd-syntax=1.0
20170312-214659 761 cmd5 - Command: [99] events e7s0c0
20170312-214659 766 cmd5 - Response: [99] 200 OK.
20170312-214659 761 cmd5 - Command: [100] dbgetxml //SWINN/254
20170312-214659 766 cmd5 - Response: [100] 343-Begin XML snippet
20170312-214659 766 cmd5 - Response: [100] 344 End XML snippet
20170312-214659 804 cmd5 - Host:/127.0.0.1 closed command interface from port: 49962
```

Would really appreciate your help to solve this one.

Best wishes

Matt

**Comment by simonhac** [comment]
@MattSwinn first thing i'd do is check that `homebridge` is using the right version of `node` and `v8` -- check out #26 to see how we tracked this down recently.

**Comment by simonhac** [comment]
unrelated, but fyi: quotes aren't needed around the numerical values. (eg. `"network": "254", "application": "56"`)

**Comment by MattSwinn** [comment]
Thanks @simonhac, I have updated and now have versions:

node: 7.7.2
v8: 5.5.372.41

I also removed the quotes around the numerical values.

But that hasn't resolved the issue.

**Comment by simonhac** [comment]
@MattSwinn just checking that you got these by adding `console.log(util.inspect(process.versions));` to `/local/lib/node_modules/homebridge/bin/homebridge` (or equivalent) rather than the command line.

(i don't know why, but as found in  #26, the command line can resolve different versions of `node` to the one used by the `homebridge` start script.)

**Comment by MattSwinn** [comment]
I hadn't checked it that way previously but I have done so now.  When trying to start homebridge, I now get:

```
Matthews-iMac:/ Matt$ homebridge
{ http_parser: '2.7.0',
  node: '7.7.2',
  v8: '5.5.372.41',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
[13/03/2017, 3:22:13 pm] Loaded plugin: homebridge-cbus
[13/03/2017, 3:22:13 pm] Registering platform 'homebridge-cbus.CBus'
[13/03/2017, 3:22:13 pm] ---
[13/03/2017, 3:22:13 pm] Loaded config.json with 0 accessories and 1 platforms.
[13/03/2017, 3:22:13 pm] ---
[13/03/2017, 3:22:13 pm] Loading 1 platforms...
[13/03/2017, 3:22:13 pm] [CBus] Initializing homebridge-cbus.CBus platform...
  cbus:client Opening connection to C-Gate… +0ms
[13/03/2017, 3:22:13 pm] Loading 0 accessories...
  cbus:client C-Gate connection open. +4ms
  cbus:client Connected to C-Gate server v2.10.6 (build 3145), syntax v1.0 +2ms
  cbus:client Configuring C-Gate session… +0ms
  cbus:client C-Gate session estabished and configured at 20023:127.0.0.1 +1ms
  cbus:platform Loading the accessories list… +0ms
/usr/local/lib/node_modules/homebridge-cbus/index.js:186
	for (let config of this.config.accessories) {
	                              ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at CBusPlatform._createAccessories (/usr/local/lib/node_modules/homebridge-cbus/index.js:186:32)
    at CBusPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/index.js:166:28)
    at Carrier.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:195:6)
    at emitOne (events.js:96:13)
    at Carrier.emit (events.js:191:7)
    at /usr/local/lib/node_modules/homebridge-cbus/node_modules/carrier/lib/carrier.js:24:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Matthews-iMac:/ Matt$ 
```
So it looks as if homebridge is using the correct version of node.

**Comment by simonhac** [comment]
thanks @MattSwinn for getting the obvious stuff out of the way.

try changing `accesories` to `accessories` and you should be on your way.

(once #32 is complete, hopefully no-one need experience this pain again.)

**Comment by simonhac** [comment]
@MattSwinn i've created a tiny pull request (#34) to ensure that no-one is caught by this exact problem again.

**Comment by MattSwinn** [comment]
Thanks @simonhac - this is why I will never make a programmer!  All working perfectly now.  Thanks for your patience.

**Comment by simonhac** [comment]
my pleasure @MattSwinn -- please feel free to open other issues as you encounter problems.
