### ISSUE TITLE
C-Bus network starting with a numeral is rejected as illegal

### ISSUE THREAD

**Issue by greiginsydney** [anthonywebb/homebridge-cbus#42]
If I'm reading this correctly, homebridge-cbus doesn't like my network as its name starts with a numeral.

The network is called "19P" and has been running here for many years successfully - so appears to be valid from a C-Bus perspective.

I changed it to "HOME" in the config.json file, restarted homebridge and we made it past that point, then failed due to the absence of a Tags file (as you'd expect given I'd made up the new network name).

`[4/14/2017, 9:34:15 PM] Loaded plugin: homebridge-cbus
[4/14/2017, 9:34:15 PM] Registering platform 'homebridge-cbus.CBus'
[4/14/2017, 9:34:15 PM] ---
[4/14/2017, 9:34:15 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/14/2017, 9:34:15 PM] ---
[4/14/2017, 9:34:15 PM] Loading 1 platforms...
[4/14/2017, 9:34:15 PM] [CBus] Initializing homebridge-cbus.CBus platform...
C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge-cbus\index.js:89
                throw new Error(`illegal client_cbusname: ${config.client_cbusname}`);
                ^

Error: illegal client_cbusname: 19P
    at new CBusPlatform (C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge-cbus\index.js:89:9)
    at Server._loadPlatforms (C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:294:32)
    at Server.run (C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:80:36)
    at module.exports (C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (C:\Users\greig\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by simonhac** [comment]
i think this will be addressed by PR #41, which should be closed very soon, thanks to @philpearson.

**Comment by anthonywebb** [comment]
@greiginsydney you can try the latest (0.6.0) and see if that works for you.  Thanks!

**Comment by greiginsydney** [comment]
Thanks all - that's resolved it!!
