### ISSUE TITLE
problem using homebridge service with homebridge-cbus and cgate on PI3

### ISSUE THREAD

**Issue by DarylMc** [anthonywebb/homebridge-cbus#54]
@simonhac @anthonywebb
my pi3 project and the image I uploaded has a problem.
To start CGate I used initd
http://addictedtopi.tumblr.com/post/96351714013/installing-c-gate-on-a-raspberry-pi

To start Homebridge I used systemd
https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi#running-homebridge-on-bootup-systemd

On reboot it seems Homebridge has trouble talking to CGate.
It works fine at setup of Homebridge systemd because CGate is already running.
On reboot Homebridge has control but does not show changes originating from the CBus network.
Restarting Homebridge service fixes it.
I think I need to delay the start of Homebridge service to make sure CGate is loaded and synced.
Could you please help point me to how to do that.
Maybe if Homebridge shut down because CGate wasn't ready could work too.

**Comment by DarylMc** [comment]
In the following I checked Homebridge service in the faulty state then restarted the service.
`pi@raspberrypi:~ $ sudo systemctl status homebridge -l
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mon 2017-05-29 15:07:59 AEST; 3min 15s ago
 Main PID: 856 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─856 homebridge

May 29 15:10:31 raspberrypi homebridge[856]: at CGateDatabase.getNetworkEntity (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:337:9)
May 29 15:10:31 raspberrypi homebridge[856]: at CGateDatabase.getTag (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:323:21)
May 29 15:10:31 raspberrypi homebridge[856]: at CBusPlatform._processEvent (/usr/lib/node_modules/homebridge-cbus/index.js:105:45)
May 29 15:10:31 raspberrypi homebridge[856]: at CBusPlatform.<anonymous> (/usr/lib/node_modules/homebridge-cbus/index.js:147:8)
May 29 15:10:31 raspberrypi homebridge[856]: at emitOne (events.js:96:13)
May 29 15:10:31 raspberrypi homebridge[856]: at CBusClient.emit (events.js:191:7)
May 29 15:10:31 raspberrypi homebridge[856]: at CBusClient._socketReceivedLine (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:634:10)
May 29 15:10:31 raspberrypi homebridge[856]: at Carrier.<anonymous> (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:175:9)
May 29 15:10:31 raspberrypi homebridge[856]: at emitOne (events.js:96:13)
May 29 15:10:31 raspberrypi homebridge[856]: at Carrier.emit (events.js:191:7)
pi@raspberrypi:~ $ sudo systemctl stop homebridge
pi@raspberrypi:~ $ sudo systemctl start homebridge
pi@raspberrypi:~ $ sudo systemctl status homebridge -l
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mon 2017-05-29 15:12:01 AEST; 1min 8s ago
 Main PID: 988 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─988 homebridge

May 29 15:12:07 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:07 GMT cbus:client matched request '[110] get //OFFICE/254/56/4 level # getOn' with response '[110] 300 //OFFICE/254/56/4: level=255' (2 pending requests)
May 29 15:12:07 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:07 GMT cbus:client rx response { commandId: 111, code: 300, matched: false, processed: true, netId: //OFFICE/254/56/2, level: 0, type: 'response', raw: '[111] 300 //OFFICE/254/56/2: level=0' }
May 29 15:12:07 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:07 GMT cbus:client matched request '[111] get //OFFICE/254/56/2 level # getOn' with response '[111] 300 //OFFICE/254/56/2: level=0' (1 pending requests)
May 29 15:12:07 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:07 GMT cbus:client rx response { commandId: 112, code: 300, matched: false, processed: true, netId: //OFFICE/254/56/8, level: 0, type: 'response', raw: '[112] 300 //OFFICE/254/56/8: level=0' }
May 29 15:12:07 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:07 GMT cbus:client matched request '[112] get //OFFICE/254/56/8 level # getOn' with response '[112] 300 //OFFICE/254/56/8: level=0' (0 pending requests)
May 29 15:12:10 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:10 GMT cbus:client sent command '[113] ramp //OFFICE/254/56/4 0% # setOn (off)'
May 29 15:12:10 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:10 GMT cbus:client rx response { commandId: 113, code: 200, matched: false, processed: true, type: 'response', raw: '[113] 200 OK: //OFFICE/254/56/4' }
May 29 15:12:10 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:10 GMT cbus:client matched request '[113] ramp //OFFICE/254/56/4 0% # setOn (off)' with response '[113] 200 OK: //OFFICE/254/56/4' (0 pending requests)
May 29 15:12:10 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:10 GMT cbus:client rx event { time: '20170529-151210', code: 730, processed: true, netId: //OFFICE/254/56/4, level: 0, sourceunit: 202, ramptime: 0, sessionId: 'cmd5', commandId: 113, type: 'event', raw: '#e# 20170529-151210 730 //OFFICE/254/56/4 eb62fd30-265a-1035-a662-8f914384ea95 new level=0 sourceunit=202 ramptime=0 sessionId=cmd5 commandId=113' }
May 29 15:12:11 raspberrypi homebridge[988]: Mon, 29 May 2017 05:12:11 GMT cbus:client rx event { time: '20170529-151211', code: 730, processed: true, netId: //OFFICE/254/56/4, level: 100, sourceunit: 3, ramptime: 0, type: 'event', raw: '#e# 20170529-151211 730 //OFFICE/254/56/4 eb62fd30-265a-1035-a662-8f914384ea95 new level=255 sourceunit=3 ramptime=0' }
`

**Comment by DarylMc** [comment]
I added a 4 min delay to homebridge service after boot and all working for now.
A large network might need even longer.

**Comment by DarylMc** [comment]
I have uploaded the modified homebridge.service  and added homebridge.timer files if it can be of assistance to anyone.
https://1drv.ms/f/s!AminzOc-NC4UgZoYBVueY_n3LIUZ8g
