### ISSUE TITLE
the plugin cannot be loaded

### ISSUE THREAD

**Issue by tonylee0000** [anthonywebb/homebridge-cbus#57]
I have a question when I installed the home bridge- bus on to raspberry pi it seemed every ok  but when I run home bridge  display cannot load that plugin  I don't know why. I use raspberry pi 3 and 5500cn to connect to cbus. Are there something wrong with it﻿

**Comment by EdwinJS** [comment]
Please provide the error log output and we can have a look at the reason why :)

**Comment by tonylee0000** [comment]
]0;pi@hassbian: ~[01;32mpi@hassbian[00m:[01;34m~ $[00m cd / [Khome/pi/.homr[Kebridge
]0;pi@hassbian: ~/.homebridge[01;32mpi@hassbian[00m:[01;34m~/.homebridge $[00m homebridgr[Ke
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[37m[6/24/2017, 3:38:01 PM][39m [1m[31m====================[39m[22m
[37m[6/24/2017, 3:38:01 PM][39m [1m[31mERROR LOADING PLUGIN homebridge-cbus:[39m[22m
[37m[6/24/2017, 3:38:01 PM][39m [1m[31mSyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)[39m[22m
[37m[6/24/2017, 3:38:01 PM][39m [1m[31m====================[39m[22m

**Comment by tonylee0000** [comment]
I installed homebridge  and then installed homebridge-cbus  onto raspberry pi3  when I run homebridge those message were displayed

**Comment by preid-iworks** [comment]
I'm getting this too on a new install when launching homebridge.

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:14:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by simonhac** [comment]
we've seen this several times before -- each time it's been due to an older (non ES6 compliant) version of nodejs attempting to run `homebridge-cbus`.

see #26.

**Comment by simonhac** [comment]
@anthonywebb and @DarylMc -- we should add a section that describes how to fix this in the README. (i would, but i don't know enough about the cause and resolution to explain it adequately. either of you?)

**Comment by DarylMc** [comment]
I spent some time with tony
I'm pretty sure it is resolved
Who knew siri could speak chinese?
With english config.json?
https://www.youtube.com/watch?v=Y3OIp-PEBvY

**Comment by anthonywebb** [comment]
@DarylMc that is really cool, thanks for the help!

**Comment by DarylMc** [comment]
@anthonywebb @simonhac 
I think tony was using my old image, old instructions and had other problems in general.

In case anyone missed it there is some compatibility problems with recent CGate and Toolkit versions.
I'm using latest CGate 2.11.1 on pi for compatibility with Toolkit 1.15.1  
I've used quite a few CGate versions recently and all worked well with the correct toolkit version.
