### ISSUE TITLE
TypeError terminates process soon after startup

### ISSUE THREAD

**Issue by simonhac** [anthonywebb/homebridge-cbus#6]
I am running homebridge-cbus for the first time, so perhaps i've done something wrong, however when i start up, the process soon terminates with a `TypeError`

full log:
```
$ homebridge
[1/8/2017, 9:18:51 PM] Loaded plugin: homebridge-cbus
[1/8/2017, 9:18:51 PM] Registering platform 'homebridge-cbus.CBus'
[1/8/2017, 9:18:51 PM] ---
[1/8/2017, 9:18:51 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/8/2017, 9:18:51 PM] ---
[1/8/2017, 9:18:51 PM] Loading 1 platforms...
[1/8/2017, 9:18:51 PM] [CBus] Initializing homebridge-cbus.CBus platform...
[1/8/2017, 9:18:51 PM] [CBus] Connecting to the local CBus server...
[1/8/2017, 9:18:51 PM] Loading 0 accessories...
[1/8/2017, 9:18:51 PM] [CBus] CBus Client is listening to CGate on 127.0.0.1... Debug: true
[1/8/2017, 9:18:51 PM] [CBus] Registering the accessories list...
[1/8/2017, 9:18:51 PM] [CBus] Initializing platform accessory 'Kitchen Nook'...
[1/8/2017, 9:18:51 PM] [CBus] Initializing platform accessory 'Kitchen Pendant'...
[1/8/2017, 9:18:51 PM] [CBus] Initializing platform accessory 'Kitchen Sink'...
[1/8/2017, 9:18:51 PM] [CBus] Initializing platform accessory 'Pantry PIR'...
[1/8/2017, 9:18:51 PM] [CBus] Initializing platform accessory 'Scullery PIR'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/8/2017, 9:18:51 PM] Homebridge is running on port 51826.
CBusStatusPacket {
  raw: '201 Service ready: Clipsal C-Gate Version: v2.10.6 (build 3145) #cmd-syntax=1.0',
  channel: 'controlStream',
  type: 'unknown',
  source: 'cbus' }
/usr/local/lib/node_modules/homebridge-cbus/cgate-client.js:313
        this.group = temp[2];
                         ^

TypeError: Cannot read property '2' of null
    at new CBusStatusPacket (/usr/local/lib/node_modules/homebridge-cbus/cgate-client.js:313:26)
    at CBusClient._resolveReceivedMessage (/usr/local/lib/node_modules/homebridge-cbus/cgate-client.js:253:23)
    at CBusClient._socketReceivedMessageEvent (/usr/local/lib/node_modules/homebridge-cbus/cgate-client.js:200:10)
    at Carrier.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/cgate-client.js:112:14)
    at emitOne (events.js:96:13)
    at Carrier.emit (events.js:188:7)
    at /usr/local/lib/node_modules/homebridge-cbus/node_modules/carrier/lib/carrier.js:24:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

for completeness, my `config.json` file is:
```
{
  "bridge": {
    "name": "Kinkora",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
 
  "description": "This is the My home HomeKit API configuration file.",
 
  "platforms": [
    {
      "platform": "homebridge-cbus.CBus",
      "name": "CBus",
      "client_ip_address": "127.0.0.1",
      "client_controlport": 20023,
      "client_eventport": 20024,
      "client_statusport": 20025,
      "client_cbusname": "SHAC",
      "client_network": 254,
      "client_application": 56,
      "client_debug": true,
      "accessories":
      [
        { "type": "dimmer", "id": "28", "name": "Kitchen Pendant" },
        { "type": "dimmer", "id": "26", "name": "Kitchen Sink" },
        { "type": "light", "id": "27", "name": "Kitchen Nook" },
        { "type": "motion", "id": "110", "name": "Scullery PIR" },
        { "type": "motion", "id": "148", "name": "Pantry PIR" }
      ]
    }
  ],
  "accessories": [ ]
}
```

**Comment by simonhac** [comment]
found it!

i usually set my c-gate config to `tag-name-output=yes`. homekit-cbus currently chokes on this, expecting a group number rather than a tag.

i reverted back to the default (`tag-name-output=no`) and it works 100%.

perhaps this is an issue i can help work around.
